In [6]:
!pip install pandas

  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
    --------------------------------------- 0.3/11.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.6 MB 4.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.6 MB 5.2 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.6 MB 5.4 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.6 MB 5.9 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.6 MB 6.2 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.6 MB 5.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.9/11.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.6 MB 5.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.7/11.6 MB 5.6 MB/s eta 0:00:01
   -----------------------------

In [14]:
import pandas as pd
import numpy as np

In [15]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
##create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["ROW1","ROW2","ROW3","ROW4","ROW5"],columns=["col1","col2","col3","col4"])

In [28]:
df.head(2)

col1  col2  col3  col4
ROW1     0     1     2     3
ROW2     4     5     6     7

In [29]:
df.tail(1)

col1  col2  col3  col4
ROW5    16    17    18    19

In [30]:
type(df)

pandas.core.frame.DataFrame

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ROW1 to ROW5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [32]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [33]:
##Indexing
##columnname,rowindex[loc],rowindex columnindex number[.iloc]
df.head()

col1  col2  col3  col4
ROW1     0     1     2     3
ROW2     4     5     6     7
ROW3     8     9    10    11
ROW4    12    13    14    15
ROW5    16    17    18    19

In [38]:
##columnname
type(df["col1"])

pandas.core.series.Series

In [37]:
df[["col1","col2","col3"]]

col1  col2  col3
ROW1     0     1     2
ROW2     4     5     6
ROW3     8     9    10
ROW4    12    13    14
ROW5    16    17    18

In [42]:
#rowindex[loc]
df.loc[["ROW2","ROW3"]]

col1  col2  col3  col4
ROW2     4     5     6     7
ROW3     8     9    10    11

In [43]:
#rowindex columnindex number[.iloc]
df.head()

col1  col2  col3  col4
ROW1     0     1     2     3
ROW2     4     5     6     7
ROW3     8     9    10    11
ROW4    12    13    14    15
ROW5    16    17    18    19

In [44]:
df.iloc[2:4,0:2]

col1  col2
ROW3     8     9
ROW4    12    13

In [45]:
df.iloc[2:,0:]

col1  col2  col3  col4
ROW3     8     9    10    11
ROW4    12    13    14    15
ROW5    16    17    18    19

In [47]:
df[["col1","col2"]]

col1  col2
ROW1     0     1
ROW2     4     5
ROW3     8     9
ROW4    12    13
ROW5    16    17

In [52]:
#convert dataframe into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [53]:
##Basic Operations
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [56]:
##create Dataframe
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["ROW1","ROW2"],columns=["col1","col2","col3"])

In [58]:
df.head()

col1  col2  col3
ROW1     1   NaN     2
ROW2     1   3.0     4

In [59]:
df.isnull().sum()

col1    0
col2    1
col3    0
dtype: int64

In [61]:
df.isnull()

col1   col2   col3
ROW1  False   True  False
ROW2  False  False  False

In [64]:
df.isnull().sum==0

False

In [66]:
df["col3"].value_counts()

col3
2    1
4    1
Name: count, dtype: int64

In [68]:
df["col2"].unique()

array([nan,  3.])

In [69]:
df>1

col1   col2  col3
ROW1  False  False  True
ROW2  False   True  True

In [70]:
df["col2"]>2

ROW1    False
ROW2     True
Name: col2, dtype: bool