In [1]:
import numpy as np

In [4]:
x=np.array([1,2,3,4])
print(x)
type(x)

[1 2 3 4]


numpy.ndarray

In [5]:
y=[1,2,3,4]
print(y)
type(y)

[1, 2, 3, 4]


list

In [8]:
%timeit [i**4 for i in range(1,9)]

2.16 µs ± 54.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%timeit np.arange(1,9)*4

5.03 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
l=[]
for i in range(1,5):
    int=int(input("Enter:"))
    l.append(int)

print(np.array(l))

Enter:1
Enter:2
Enter:3
Enter:4
['1' '2' '3' '4']


 ar2=np.array([[1,2,3],[)

In [20]:
ar2=np.array([[1,2,3],[1,2,3]])
print(ar2)
print(ar2.ndim)

ar2=np.array([[1,2,3],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [1 2 3]]
2
[list([1, 2, 3]) list([1, 2, 3, 4])]
1


C:\Users\lokes\AppData\Local\Temp\ipykernel_6572\1557427733.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2=np.array([[1,2,3],[1,2,3,4]])


In [22]:
ar3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [24]:
ar=np.array([1,2,3],ndmin=10)
print(ar)
print(ar.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [27]:
ar_zeros=np.zeros(4)
ar1_zeros=np.zeros((3,4))
print(ar_zeros)
print()
print(ar1_zeros)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
ar_ones=np.ones(4)
ar1_ones=np.ones((3,4))
print(ar_ones)
print()
print(ar1_ones)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [31]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [32]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [34]:
ar_lin=np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# rand()

In [35]:
var=np.random.rand(4)
print(var)

[0.05775715 0.02858274 0.29942603 0.58211639]


In [36]:
var1=np.random.rand(2,5)
print(var1)

[[0.60549045 0.20233252 0.7205312  0.54639612 0.85661528]
 [0.91026164 0.80485588 0.49514661 0.73768319 0.17647423]]


In [38]:
var2=np.random.randn(2,5)
print(var2)

[[-1.01312927 -1.0363219   0.07051125 -0.24987406 -0.50479602]
 [-0.01809872  0.50250553  1.07608265  0.02456707  0.27730417]]


In [40]:
var3=np.random.ranf(2)
print(var3)

[0.70887629 0.45456127]


In [44]:
var4=np.random.randint(2,5,4)
print(var4)

[3 2 4 4]


# datatype
import numpy as np
x=np.array([1,2,3,4])
print(x)
type(x)
print(x.dtype)

In [3]:
import numpy as np
x=np.array([1.3,2.7,3.9,4.0])
print(x)
type(x)
print(x.dtype)

[1.3 2.7 3.9 4. ]
float64


In [4]:
import numpy as np
x=np.array(["l","o","k"])
print(x)
type(x)
print(x.dtype)

['l' 'o' 'k']
<U1


In [5]:
import numpy as np
x=np.array(["l","o","k",1,2,3])
print(x)
type(x)
print(x.dtype)

['l' 'o' 'k' '1' '2' '3']
<U11


In [9]:
import numpy as np
x=np.array([1,2,3],dtype=np.int8)
print(x.dtype)

int8


In [11]:
import numpy as np
x=np.array([1,2,3],dtype="f")
print(x)
print(x.dtype)

[1. 2. 3.]
float32


In [17]:
import numpy as np
x=np.array([1,2,3])
new=np.float32(x)
new1=np.int_(new)
print(x)
print(x.dtype)
print(new)
print(new.dtype)
print(new1)
print(new1.dtype)

[1 2 3]
int32
[1. 2. 3.]
float32
[1 2 3]
int32


In [21]:
x3=np.array([1,2,3])
new=x3.astype(float)
print(x3)
print(new)

[1 2 3]
[1. 2. 3.]


# Arithmetic operations in numpy array

In [23]:
import numpy as np

var=np.array([1,2,3,4])

varadd=var+3

print(varadd)

[4 5 6 7]


In [24]:

var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])

print(np.add(var1,var2))

[2 4 6 8]


In [25]:

var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])

print(np.subtract(var1,var2))

[0 0 0 0]


# 2d array

In [26]:
import numpy as np

var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])

varadd=np.add(var1,var2)

print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


# Shape

In [30]:
import numpy as np

var=np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [37]:
var1=np.array([1,2,3,4],ndmin=4)

print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


# Reshape

In [45]:
var2=np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x=var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [48]:
var3=np.array([1,2,3,4,5,6,1,2,3,4,5,6])
print(var3)
print(var3.ndim)

print()

x=var3.reshape(2,3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3 4 5 6]
1

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
3


In [51]:
var3=np.array([1,2,3,4,5,6,1,2,3,4,5,6])
print(var3)
print(var3.ndim)

print()

x=var3.reshape(2,3,2)

print(x)
print(x.ndim)
print()

x2=x.reshape(-1)

print(x2)
print(x2.ndim)

[1 2 3 4 5 6 1 2 3 4 5 6]
1

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
3

[1 2 3 4 5 6 1 2 3 4 5 6]
1


# Broadcasting 

In [54]:
import numpy as np

var1=np.array([1,2,3,4])

var2=np.array([1,2,3,4])

print(var1+var2)

[2 4 6 8]


In [60]:
var1=np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()


var2=np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()
print(var1+var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [66]:
x=np.array([[1],[2]])
print(x)
print(x.shape)
print()

y=np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)
print()
print(x+y)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[2 3 4]
 [3 4 5]]


# indexing

In [3]:
import numpy as np

var=np.array([1,2,3,4])

print(var[0])
print(var[1])
print(var[2])
print(var[-1])

1
2
3
4


In [14]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print(var1.ndim)
print(var1[0,0])

[[1 2 3 4]
 [1 2 3 4]]
2
1


In [19]:
var3=np.array([[[1,2],[6,7]]])
print(var3)
print(var3.ndim)
print(var3[0,1,1])

[[[1 2]
  [6 7]]]
3
7


# slicing

In [26]:
import numpy as np

var=np.array([1,2,3,4])

print(var[0:4])
print(var[0:])
print(var[:4])
print(var[::2])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 3]


In [33]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
print(var2)
print(var2.ndim)
print(var2[0,1:3])

[[1 2 3 4]
 [1 2 3 4]]
2
[2 3]


In [43]:
var3=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print(var3[0,1,1:])

[[[1 2 3 4]
  [1 2 3 4]]]
3
[2 3 4]


# iteration

In [54]:
var1=np.array([1,2,3,4])


for i in var1:
    print(i)

1
2
3
4


In [58]:
var2=np.array([[1,2,3,4],[1,2,3,4]])

for j in var2:
    print(j)
    
print()


for k in var2:
    for l in k:
        print(l)

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [60]:
var3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for j in var3:
    print(j)
    
print()


for i in var3:
    for j in i:
        for k in j:
            print(k)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4
1
2
3
4


In [64]:
var4=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for j in np.nditer(var4):
    print(j)
    
for i in np.nditer(var4,flags=["buffered"],op_dtypes=["S"]):
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [65]:
var4=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for j in np.ndenumerate(var4):
    print(j)
    

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 3)
((0, 1, 3), 4)
((0, 2, 0), 1)
((0, 2, 1), 2)
((0, 2, 2), 3)
((0, 2, 3), 4)


# copy vs view

In [72]:
import numpy as np

var=np.array([1,2,3,4])

co=var.copy()

var[1]=30

print("var:",var)
print("copy:",co)

var: [ 1 30  3  4]
copy: [1 2 3 4]


In [73]:
x=np.array([9,8,7,6,5])

vi=x.view()

x[1]=10

print("x:",x)
print("view:",vi)

x: [ 9 10  7  6  5]
view: [ 9 10  7  6  5]


# join& split

In [75]:
import numpy as np

var=np.array([1,2,3,4])
var1=np.array([9,8,7,6])

ar=np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [81]:
var2=np.array([[1,2],[3,4]])
var3=np.array([[9,8],[7,6]])

ar_new=np.concatenate((var2,var3),axis=1)

print(ar_new)

[[1 2 9 8]
 [3 4 7 6]]


In [87]:
import numpy as np

var4=np.array([1,2,3,4])
var5=np.array([9,8,7,6])

ar1=np.stack((var4,var5),axis=1)
ar2=np.hstack((var4,var5))#row
ar3=np.vstack((var4,var5))#colums
ar4=np.dstack((var4,var5))#height

print(ar1)
print()
print(ar2)
print()
print(ar3)
print()
print(ar4)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# split

In [94]:
import numpy as np

var=np.array([1,2,3,4])

print(var)

ar=np.split(var,2)

print(ar)
print(ar[0])

[1 2 3 4]
[array([1, 2]), array([3, 4])]
[1 2]


In [100]:
var1=np.array([[1,2],[3,4],[5,6]])

print(var1)

ar=np.split(var1,3)

print(ar)
print()
# print(ar1)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]



Numpy Arrays Functions

In [9]:
#search 

import numpy as np
var=np.array([1,2,3,2,4,5,6,7,8,9])

x=np.where((var/2)==0)
print(x)

(array([], dtype=int64),)


Search sorted array

In [14]:
var1=np.array([1,2,3,4,8,9,10])

x=np.searchsorted(var1,[5,6,7],side="right")
print(x)

[4 4 4]


#Sort

In [15]:
var2=np.array([2,6,7,3,4,1])

x=np.sort(var2)
print(x)

[1 2 3 4 6 7]


In [17]:
var3=np.array(["d","b","f","s"])

x=np.sort(var3)
print(x)

['b' 'd' 'f' 's']


In [18]:
var4=np.array([[2,6,3],[4,2,1],[3,1,5]])

x=np.sort(var4)
print(x)

[[2 3 6]
 [1 2 4]
 [1 3 5]]


Filter

In [21]:
a=np.array(["a","s","d","f"])

f=[True,False,False,True]

x=a[f]

print(x)

['a' 'f']


Arithmatic Fuctions Shuffle

In [22]:
import numpy as np

var=np.array([1,2,3,4,5,6])

np.random.shuffle(var)

print(var)

[6 2 4 1 5 3]


In [30]:
var1=np.array([1,2,3,4,5,6,3,4,7,6])

x=np.unique(var1)
y=np.unique(var1,return_index=True,return_counts=True)
print(x)
print()
print(y)

[1 2 3 4 5 6 7]

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 8], dtype=int64), array([1, 1, 2, 2, 1, 2, 1], dtype=int64))


In [31]:
var2=np.array([1,2,3,4,5,6,7])

y=np.resize(var2,(2,3))

print(y)

[[1 2 3]
 [4 5 6]]


In [40]:
var2=np.array([1,2,3,4,5,6,7])

y=np.resize(var2,(3,3))
print(y)
print()
print(y.flatten())
print("Flatten:",y.flatten(order="F"))
print("Ravel:",np.ravel(y,order="F"))

[[1 2 3]
 [4 5 6]
 [7 1 2]]

[1 2 3 4 5 6 7 1 2]
Flatten: [1 4 7 2 5 1 3 6 2]
Ravel: [1 4 7 2 5 1 3 6 2]


insert and delete arrays fuctions

In [43]:
import numpy as np
n=int(input("enter the range of array:"))
arr=[]
for i in range(1,n):
    array=int(input("Enter elements:"))
    arr.append(array)
print(arr)


enter the range of array: 5
Enter elements: 1
Enter elements: 2
Enter elements: 3
Enter elements: 4


[1, 2, 3, 4]


In [45]:
var=np.array([1,2,3,4,5])
print(var)
v=np.insert(var,2,12)
print(v)
c=np.insert(var,(2,4),12)
print(c)

[1 2 3 4 5]
[ 1  2 12  3  4  5]
[ 1  2 12  3  4 12  5]


In [61]:
var2=np.array([[1,2,3],[1,2,3]])
v2=np.insert(var2,2,[12,23],axis=1)
print(v2)

v3=np.insert(var2,1,[12],axis=0)
print()
print(v3)

v4=np.append(var2,[[12,34,66]],axis=0)
print()
print(v4)

[[ 1  2 12  3]
 [ 1  2 23  3]]

[[ 1  2  3]
 [12 12 12]
 [ 1  2  3]]

[[ 1  2  3]
 [ 1  2  3]
 [12 34 66]]


Delete

In [62]:
var1=np.array([1,2,3,4])

print(var1)

d=np.delete(var1,2)

print(d)

[1 2 3 4]
[1 2 4]


create matrix in numpy

In [65]:
import numpy as np

var=np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [66]:
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


Arithmetic operation in matrix

In [72]:
import numpy as np

var=np.matrix([[1,2],[1,2]])
var1=np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print(var+var1)
print()
print(var-var1)
print()
print(var*var1)
print()
print(var.dot(var1))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>
[[2 4]
 [2 4]]

[[0 0]
 [0 0]]

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [74]:
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


Transpose

In [79]:
import numpy as np

var=np.matrix([[1,2,3],[1,2,3]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


In [83]:
var2=np.matrix([[1,2],[3,4]])
print(var2)
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [87]:
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [93]:
var4=np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [97]:
var5=np.matrix([[1,2,3],[3,4,5],[1,2,6]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 4 5]
 [1 2 6]]

-6.000000000000003
